### ISSUE TITLE
Interaction of widget.launchbar and RectDecoration

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#117]
qtile-extra: r142.e522e59-1

There is a clear issue visible here:
![image](https://user-images.githubusercontent.com/27446196/191796936-9cd741ca-e4a5-4302-9932-822e59424681.png)

And it seems related to the problem described here :
https://www.reddit.com/r/qtile/comments/xbd6oq/qtileextras_grouping_rectdecoration/

```
decor = {
    "decorations": [
        RectDecoration(
            colour=colors[6],
            line_width= 2,
            radius=20,
            filled=True,
            padding_y=5,
            padding_x=0,
            group=True,
        )
    ],
}
```

```
 widget.LaunchBar(progs=[
                        ('org.gnome.Terminal', 'gnome-terminal', 'Launch terminal'),
                        ('chromium', 'chromium', 'Launch Chromium'),
                        ('steam', 'steam', 'Launch Steam'),
                        ('evolution', 'evolution', 'Launch Evolution'),
                        ('discord', 'discord', 'Launch Discord'),
                        ('spotify', 'spotify', 'Launch Spotify'),
                                       ], 
                        padding = 15, 
                        **decor
```

**Comment by elParaguayo** [comment]
Thanks for the report. The issue is actually this line in `LaunchBar`:
https://github.com/qtile/qtile/blob/master/libqtile/widget/launchbar.py#L241

I'm not sure why `clear` needs to be called multiple times for the widget but that triggers the drawing of the decoration. Commenting out that line may fix it.

I can test later but I have very little spare time for the next few weeks.
